name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # 每天自动运行一次
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          since: "2024-07-24"  # 自定义起始日期
          outputs: |
            dist/only-svg/github-contribution-grid-snake.svg?palette=github-light&color_snake=#800080&color_dots=#FFA500
            dist/only-svg/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#800080&color_dots=#FFA500
            dist/only-svg/github-contribution-grid-snake-blue.svg?palette=github-light&color_snake=#800080&color_dots=#FFA500

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          since: "2024-07-24"  # 自定义起始日期
          outputs: |
            dist/docker/github-contribution-grid-snake.gif?palette=github-light&color_snake=#800080&color_dots=#FFA500

      - name: Ensure the generated file exists
        run: |
          ls dist
          test -f dist/only-svg/github-contribution-grid-snake.svg
          test -f dist/only-svg/github-contribution-grid-snake-dark.svg
          test -f dist/only-svg/github-contribution-grid-snake-blue.svg
          test -f dist/docker/github-contribution-grid-snake.gif

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
